// SPDX-License-Identifier: GPL-3.0-or-later
/*
 * GeekMagicO - a fork of GeekMagic Open Firmware
 * <https://github.com/Times-Z/GeekMagic-Open-Firmware>
 *
 * Copyright (C) 2026 Times-Z
 * Copyright (C) 2026 GeekMagicO contributors
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include <Arduino.h>
#include <LittleFS.h>

#include "screens/WeatherScreens.h"
#include "screens/DrawUtils.h"
#include "display/DisplayManager.h"
#include "config/ConfigManager.h"
#include "time/TimeService.h"
#include "wireless/WiFiManager.h"

extern ConfigManager configManager;

namespace {
constexpr uint16_t BG_COLOR = LCD_BLACK;
constexpr uint16_t MUTED = 0x8410;
constexpr uint16_t ACCENT = 0xFD20;

// Panel is a fixed 240x240, so the layouts are written as literal geometry.
// NOLINTBEGIN(readability-magic-numbers)
constexpr int16_t PANEL_W = 240;
constexpr int16_t GIF_BOX = 80;

// Weather clock geometry. The icon and the temperature share a row and are
// centred on the same axis (icon 80..160, temperature 100..140, both centred
// on y=120). The condition and detail lines get the full panel width because
// they do not fit beside the icon: "Partly cloudy" is 156px and
// "H100%  100.0km/h" is 192px, so right-aligning either one to x=232 puts its
// left edge inside the icon box.
constexpr int16_t ICON_X = 8;
constexpr int16_t ICON_Y = 80;
constexpr int16_t TIME_Y = 8;
constexpr int16_t DATE_Y = 54;
constexpr int16_t TEMP_Y = 100;
constexpr int16_t CONDITION_Y = 172;
constexpr int16_t DETAIL_Y = 196;

// The fallback message shares the condition row rather than sitting in the
// icon box, where it would be drawn over by a running animation.
constexpr int16_t NO_DATA_Y = CONDITION_Y;
constexpr int16_t TEXT_RIGHT = 232;
// NOLINTEND(readability-magic-numbers)

// Bundled per-condition animations, indexed by WeatherCondition. Kept in
// PROGMEM because plain literals land in .rodata, which is DRAM on this part.
// Generated by scripts/build-weather-gifs.sh; see CLAUDE.md.
//
// NOLINTBEGIN(modernize-avoid-c-arrays): PROGMEM needs real C arrays. std::array
// has no attribute-carrying storage the linker will place in flash, so wrapping
// these would silently move ~200 bytes of strings back into DRAM.
const char WX_GIF_UNKNOWN[] PROGMEM = "/gif/wx-unknown.gif";
const char WX_GIF_CLEAR[] PROGMEM = "/gif/wx-clear.gif";
const char WX_GIF_PARTLY[] PROGMEM = "/gif/wx-partly-cloudy.gif";
const char WX_GIF_CLOUDY[] PROGMEM = "/gif/wx-cloudy.gif";
const char WX_GIF_FOG[] PROGMEM = "/gif/wx-fog.gif";
const char WX_GIF_DRIZZLE[] PROGMEM = "/gif/wx-drizzle.gif";
const char WX_GIF_RAIN[] PROGMEM = "/gif/wx-rain.gif";
const char WX_GIF_SNOW[] PROGMEM = "/gif/wx-snow.gif";
const char WX_GIF_SLEET[] PROGMEM = "/gif/wx-sleet.gif";
const char WX_GIF_THUNDER[] PROGMEM = "/gif/wx-thunder.gif";

PGM_P const WX_GIF_PATHS[] PROGMEM = {
    WX_GIF_UNKNOWN, WX_GIF_CLEAR, WX_GIF_PARTLY,  WX_GIF_CLOUDY, WX_GIF_FOG,
    WX_GIF_DRIZZLE, WX_GIF_RAIN,  WX_GIF_SNOW,    WX_GIF_SLEET,  WX_GIF_THUNDER,
};

// NOLINTEND(modernize-avoid-c-arrays)

constexpr size_t WX_GIF_COUNT = sizeof(WX_GIF_PATHS) / sizeof(WX_GIF_PATHS[0]);
constexpr size_t WX_GIF_PATH_MAX = 32;

// The sentinel weather.gif carries for "pick the icon from the conditions".
// It cannot collide with an uploaded file: the upload allowlist only accepts
// .jpg/.jpeg/.gif (FileStore::isDisplayable).
constexpr const char* GIF_MODE_AUTO = "auto";

/**
 * @brief Format the current temperature for display
 */
auto formatTemp(float celsius) -> String {
    return String(WeatherClient::toDisplayTemp(celsius), 0) + String(WeatherClient::temperatureUnit());
}

/**
 * @brief Start the bundled animation for a condition in the icon slot
 *
 * The bundled GIFs are ordinary files the user is free to delete to reclaim
 * space, so a missing one is expected rather than exceptional: the caller
 * falls back to the vector glyph for that condition alone.
 *
 * @param condition A WeatherCondition value
 *
 * @return true when playback started
 */
auto startConditionGif(uint8_t condition) -> bool {
    if (condition >= WX_GIF_COUNT) {
        return false;
    }

    std::array<char, WX_GIF_PATH_MAX> path{};
    strncpy_P(path.data(), reinterpret_cast<PGM_P>(pgm_read_ptr(&WX_GIF_PATHS[condition])), path.size() - 1);

    if (!LittleFS.exists(path.data())) {
        return false;
    }

    return DisplayManager::playGifAt(String(path.data()), ICON_X, ICON_Y, GIF_BOX, GIF_BOX);
}
}  // namespace

// NOLINTBEGIN(readability-magic-numbers)

/**
 * @brief Paint the weather clock chrome and start the icon animation if set
 *
 * @return void
 */
void WeatherClockScreen::enter() {
    DisplayManager::getGfx()->fillScreen(BG_COLOR);

    _timeCache = "";
    _dateCache = "";
    _tempCache = "";
    _conditionCache = "";
    _detailCache = "";
    _noDataCache = "";
    _iconCondition = 0xFF;
    _gifStarted = false;

    // A GIF the user picked on the Weather page. "auto" is resolved in tick()
    // instead, because it depends on a condition that may not have arrived yet.
    const std::string& gifName = configManager.settings.weather.gif;
    if (!gifName.empty() && gifName != GIF_MODE_AUTO) {
        const String path = String("/gif/") + gifName.c_str();
        if (LittleFS.exists(path)) {
            _gifStarted = DisplayManager::playGifAt(path, ICON_X, ICON_Y, GIF_BOX, GIF_BOX);
        }
    }
}

/**
 * @brief Stop any GIF the screen started
 *
 * @return void
 */
void WeatherClockScreen::leave() {
    if (_gifStarted) {
        DisplayManager::stopGifQuiet();
        _gifStarted = false;
    }
}

/**
 * @brief Repaint the changed parts of the weather clock
 *
 * @return void
 */
void WeatherClockScreen::tick() {
    const LocalTime local = TimeService::now();
    const TimeSettings& timeCfg = configManager.settings.time;
    const WeatherNow& weather = WeatherClient::current();

    const bool autoIcon = (configManager.settings.weather.gif == GIF_MODE_AUTO);

    DrawUtils::cachedText(PANEL_W / 2, TIME_Y, TimeService::formatTime(local, timeCfg.format12h, false), _timeCache, 5,
                          timeCfg.hour_color, BG_COLOR, ALIGN_CENTER);

    DrawUtils::cachedText(PANEL_W / 2, DATE_Y, TimeService::formatDate(local, timeCfg.date_format.c_str()), _dateCache,
                          2, MUTED, BG_COLOR, ALIGN_CENTER);

    if (!weather.valid) {
        // Clear whatever was painted the last time weather was valid so it
        // doesn't linger behind the fallback message.
        DrawUtils::cachedText(TEXT_RIGHT, TEMP_Y, "", _tempCache, 5, ACCENT, BG_COLOR, ALIGN_RIGHT);
        DrawUtils::cachedText(PANEL_W / 2, CONDITION_Y, "", _conditionCache, 2, MUTED, BG_COLOR, ALIGN_CENTER);
        DrawUtils::cachedText(PANEL_W / 2, DETAIL_Y, "", _detailCache, 2, MUTED, BG_COLOR, ALIGN_CENTER);

        if (_iconCondition != 0xFF) {
            // A user's GIF is decoration and keeps playing. An auto icon is a
            // claim about the weather, so it has to go when the data does --
            // otherwise rain keeps falling next to "No weather data".
            if (autoIcon && _gifStarted) {
                DisplayManager::stopGifQuiet();
                _gifStarted = false;
            }

            if (!_gifStarted) {
                DisplayManager::getGfx()->fillRect(ICON_X, ICON_Y, GIF_BOX, GIF_BOX, BG_COLOR);
            }

            _iconCondition = 0xFF;
        }

        DrawUtils::cachedText(PANEL_W / 2, NO_DATA_Y, "No weather data", _noDataCache, 2, MUTED, BG_COLOR, ALIGN_CENTER);
        return;
    }

    if (_noDataCache.length() != 0) {
        DrawUtils::cachedText(PANEL_W / 2, NO_DATA_Y, "", _noDataCache, 2, MUTED, BG_COLOR, ALIGN_CENTER);
    }

    if (weather.condition != _iconCondition) {
        if (autoIcon) {
            // Only auto mode reacts to the condition. A user GIF, or the lack
            // of one, was already settled in enter().
            const bool wasPlaying = _gifStarted;
            _gifStarted = startConditionGif(weather.condition);

            // A deleted animation is not an error, it drops this one condition
            // back to the vector glyph -- but the previous one is still running
            // and would animate underneath it.
            if (!_gifStarted && wasPlaying) {
                DisplayManager::stopGifQuiet();
            }
        }

        if (!_gifStarted) {
            DrawUtils::weatherGlyph(ICON_X, ICON_Y, GIF_BOX, weather.condition, BG_COLOR);
        }

        _iconCondition = weather.condition;
    }

    DrawUtils::cachedText(TEXT_RIGHT, TEMP_Y, formatTemp(weather.tempC), _tempCache, 5, ACCENT, BG_COLOR, ALIGN_RIGHT);
    DrawUtils::cachedText(PANEL_W / 2, CONDITION_Y, WeatherClient::conditionLabel(weather.condition), _conditionCache, 2,
                          MUTED, BG_COLOR, ALIGN_CENTER);

    const String detail = String("H") + String(weather.humidity) + "%  " +
                          String(WeatherClient::toDisplayWind(weather.windMs), 1) + WeatherClient::windUnit();
    DrawUtils::cachedText(PANEL_W / 2, DETAIL_Y, detail, _detailCache, 2, MUTED, BG_COLOR, ALIGN_CENTER);
}

/**
 * @brief Paint the forecast chrome and request a forecast
 *
 * @return void
 */
void WeatherForecastScreen::enter() {
    auto* gfx = DisplayManager::getGfx();
    gfx->fillScreen(BG_COLOR);

    _headerCache = "";
    _rangeCache.fill(String());
    _conditionCache.fill(0xFF);

    gfx->fillRect(0, 0, PANEL_W, 30, 0x18E3);
    DrawUtils::drawText(PANEL_W / 2, 11, "FORECAST", 2, LCD_WHITE, 0x18E3, ALIGN_CENTER);

    // Fetching here rather than in tick() keeps the second HTTP request off
    // the loop for every theme that does not show a forecast.
    if (!_fetched || (millis() - _lastFetchMs) > REFRESH_INTERVAL_MS) {
        if (WiFiManager::isConnected() && WeatherClient::refreshForecast()) {
            _fetched = true;
            _lastFetchMs = millis();
        }
    }
}

/**
 * @brief Repaint the forecast columns
 *
 * @return void
 */
void WeatherForecastScreen::tick() {
    const WeatherForecast& forecast = WeatherClient::forecast();

    if (!forecast.valid) {
        DrawUtils::cachedText(PANEL_W / 2, 110, "No forecast data", _headerCache, 2, MUTED, BG_COLOR, ALIGN_CENTER);
        return;
    }

    static constexpr std::array<const char*, FORECAST_DAYS> LABELS = {"TODAY", "TOMORROW", "IN 2 DAYS"};
    constexpr int16_t rowH = 66;
    constexpr int16_t rowTop = 36;

    for (size_t i = 0; i < FORECAST_DAYS; ++i) {
        const ForecastDay& day = forecast.days[i];
        if (!day.valid) {
            continue;
        }

        const auto rowY = static_cast<int16_t>(rowTop + (static_cast<int16_t>(i) * rowH));

        if (day.condition != _conditionCache[i]) {
            DrawUtils::weatherGlyph(6, rowY, 56, day.condition, BG_COLOR);
            _conditionCache[i] = day.condition;
        }

        // +8/+24 rather than +6/+22: the label and range together span 40px,
        // which centres on the 56px icon's axis only from here.
        DrawUtils::drawText(74, rowY + 8, LABELS[i], 1, MUTED, BG_COLOR, ALIGN_LEFT);

        const String range = String(WeatherClient::toDisplayTemp(day.maxC), 0) + "/" +
                             String(WeatherClient::toDisplayTemp(day.minC), 0) +
                             String(WeatherClient::temperatureUnit());
        DrawUtils::cachedText(74, rowY + 24, range, _rangeCache[i], 3, ACCENT, BG_COLOR, ALIGN_LEFT);
    }
}

/**
 * @brief Paint the simple weather clock chrome
 *
 * @return void
 */
void SimpleWeatherClockScreen::enter() {
    DisplayManager::getGfx()->fillScreen(BG_COLOR);

    _timeCache = "";
    _tempCache = "";
}

/**
 * @brief Repaint the simple weather clock
 *
 * @return void
 */
void SimpleWeatherClockScreen::tick() {
    const LocalTime local = TimeService::now();
    const TimeSettings& timeCfg = configManager.settings.time;
    const WeatherNow& weather = WeatherClient::current();

    DrawUtils::cachedText(PANEL_W / 2, 66, TimeService::formatTime(local, timeCfg.format12h, false), _timeCache, 6,
                          timeCfg.hour_color, BG_COLOR, ALIGN_CENTER);

    const String temp = weather.valid ? formatTemp(weather.tempC) : String("--");
    DrawUtils::cachedText(PANEL_W / 2, 140, temp, _tempCache, 4, ACCENT, BG_COLOR, ALIGN_CENTER);
}

// NOLINTEND(readability-magic-numbers)
