import subprocess
import os
from SCons.Script import DefaultEnvironment

env = DefaultEnvironment()

# Only this fork's tags may name a build. Upstream tags land in the repo the
# moment anyone fetches from Times-Z, and plain --tags would happily pick one:
# that is where a device reporting "v1.4.0-10-gf62a-dev" came from, for a
# version that exists nowhere in this history.
TAG_GLOB = "v*-geekmagico"


def _git(project_dir, *args):
    return (
        subprocess.check_output(
            ["git", *args], cwd=project_dir, stderr=subprocess.DEVNULL
        )
        .decode()
        .strip()
    )


def get_git_version(project_dir):
    try:
        return _git(
            project_dir,
            "describe",
            "--tags",
            "--match",
            TAG_GLOB,
            "--dirty=-dev",
            "--broken=-dev",
            "--abbrev=2",
        )
    except Exception:
        pass

    # No matching tag (shallow clone, exported tree, tags not fetched): still
    # report something traceable rather than "unknown".
    try:
        return "0.0.0-" + _git(project_dir, "rev-parse", "--short=7", "HEAD")
    except Exception:
        return "0.0.0-unknown"

project_dir = env.get("PROJECT_DIR")
header_dir = os.path.join(project_dir, "include")
header_path = os.path.join(header_dir, "project_version.h")

git_ver = get_git_version(project_dir)

new_content = f"""// This file is auto-generated by scripts/git_version.py.
// Please do not edit manually.
#pragma once

#ifndef PROJECT_VER
#define PROJECT_VER "{git_ver}"
#endif

static const char PROJECT_VER_STR[] = "{git_ver}";
"""

def update_file_if_changed(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    
    should_write = True
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            old_content = f.read()
            if old_content == content:
                should_write = False

    if should_write:
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"[git_version] Updated: {path} (Version: {git_ver})")
    else:
        print(f"[git_version] No changes detected (Version: {git_ver})")

update_file_if_changed(header_path, new_content)
